# Generated by Django 5.0.6 on 2024-07-02 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0004_searchhistory_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='last_fetched',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
